# Generated by Django 3.2 on 2021-07-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail_img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
