# Generated by Django 3.2 on 2021-07-20 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0002_blog_thumbnail_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 20, 23, 36, 14, 964537)),
        ),
    ]
