# Generated by Django 3.2 on 2021-07-20 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0007_auto_20210720_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 21, 0, 2, 51, 506355)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail_img',
            field=models.ImageField(upload_to='blog_thumbnails/'),
        ),
    ]
