# Generated by Django 3.2 on 2021-07-20 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0008_auto_20210721_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUtilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(upload_to='site_utilities')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 21, 2, 2, 8, 279875)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail_img',
            field=models.ImageField(upload_to='blog_thumbnails'),
        ),
    ]
