# Generated by Django 3.2 on 2021-07-21 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0009_auto_20210721_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs_mail', models.EmailField(max_length=300)),
                ('subs_first_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 21, 10, 52, 35, 525795)),
        ),
    ]
