# Generated by Django 3.2 on 2021-07-21 06:21

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0010_auto_20210721_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me_avatar', models.ImageField(upload_to='about_me_picture')),
                ('about_me_description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 21, 12, 21, 25, 514282)),
        ),
    ]
