# Generated by Django 3.2 on 2021-07-21 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0012_auto_20210721_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageslider',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 21, 12, 58, 35, 618795)),
        ),
    ]
