# Generated by Django 3.2 on 2021-07-21 08:25

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0013_auto_20210721_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteutilities',
            name='about_us_avatar',
            field=models.ImageField(default=1, upload_to='site_utilities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteutilities',
            name='about_us_description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 21, 14, 25, 8, 73868)),
        ),
    ]
