# Generated by Django 3.2 on 2021-07-21 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0014_auto_20210721_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteutilities',
            name='site_logo',
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 21, 14, 39, 53, 419520)),
        ),
    ]
