# Generated by Django 3.2 on 2021-07-21 08:42

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0015_auto_20210721_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteutilities',
            name='help_text',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 21, 14, 42, 10, 904893)),
        ),
    ]
