# Generated by Django 3.2 on 2021-07-21 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0018_auto_20210721_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteutilities',
            name='site_logo',
            field=models.ImageField(default=1, upload_to='site_utilities'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 21, 16, 3, 4, 811724)),
        ),
    ]
