# Generated by Django 3.2 on 2021-07-21 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0020_auto_20210721_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteutilities',
            name='disclaimer',
        ),
        migrations.RemoveField(
            model_name='siteutilities',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='siteutilities',
            name='site_logo',
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 21, 16, 17, 33, 846433)),
        ),
    ]
