# Generated by Django 3.2 on 2021-07-24 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0021_auto_20210721_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 24, 23, 51, 54, 845132)),
        ),
    ]
