# Generated by Django 3.2 on 2021-07-26 10:26

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0022_alter_blog_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteutilities',
            name='home_first_section_heading',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteutilities',
            name='home_second_section_heading',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 26, 16, 26, 43, 781791)),
        ),
    ]
